extends:
  - plugin:import/typescript
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/naming-convention':
    - error
    - selector: default
      format:
        - strictCamelCase
    - selector: interface
      format:
        - StrictPascalCase
      prefix:
        - 'I'
    - selector: class
      format:
        - StrictPascalCase
    - selector: enum
      format:
        - StrictPascalCase
    - selector: enumMember
      format:
        - StrictPascalCase
    - selector: typeAlias
      format:
        - StrictPascalCase
      prefix:
        - 'T'
    - selector: typeParameter
      format:
        - StrictPascalCase

  'import/no-relative-parent-imports':
    - error