name: Publish to NPM
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout from repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build library
        run: npm run build
      - name: Publish library
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}